name: Test_get_artifacts
on:
  workflow_dispatch: # allow manual triggering
jobs:
  get-dracon-db-from-artifacts:
    runs-on: ubuntu-latest
    name: Get the latest dracon db
    steps:
      - name: Get the latest dracon db step
        id: db_get
        uses: northdpole/dracon-load-latest-database-action@v0
        with:
          OUTPUT_DIR: $GITHUB_WORKSPACE
      # Use the output from the `hello` step
      - name: debug
        run: echo $GITHUB_WORKSPACE; ls -lah $GITHUB_WORKSPACE; find $GITHUB_WORKSPACE -iname hi