name: Run dracon
on:
  workflow_dispatch: # allow manual triggering
jobs:
    build:
      name: run-security-scans
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: make-dirs
          run: |
            ls -lah $GITHUB_WORKSPACE
            tmp=$(mktemp -d -p $GITHUB_WORKSPACE)
            # cp -r $t $GITHUB_WORKSPACE
            # tmp=$GITHUB_WORKSPACE/$(basename $t)
            # echo $tmp
            ls -lah $tmp
            echo "DRACON_DIR=$(basename $tmp)" >> $GITHUB_ENV
            mkdir -p $tmp/tool-out $tmp/producer-out $tmp/enricher-out $tmp/enricher-db
        - name: run_gosec
          run: docker run -v $GITHUB_WORKSPACE:/code  securego/gosec -fmt json -r -no-fail -quiet -out /code/${{ env.DRACON_DIR }}/tool-out/gosec_out.json /code/...
        - name: debug0
          run: ls -lah $GITHUB_WORKSPACE; cat $GITHUB_WORKSPACE/${{ env.DRACON_DIR }}/tool-out/gosec_out.json
        - name:  parse_gosec
          run: |
            docker run -v $GITHUB_WORKSPACE:/code  \
            thoughtmachine/dracon-producer-gosec \
            -in /code/${{ env.DRACON_DIR }}/tool-out/gosec_out.json \
            -out /code/${{env.DRACON_DIR}}/producer-out/gosec-producer-out
        - name: debug1
          run: ls -lah $GITHUB_WORKSPACE/${{ env.DRACON_DIR }}; cat $GITHUB_WORKSPACE/${{ env.DRACON_DIR }}/producer-out/gosec-producer-out
        - name: fetch_db
          uses: northdpole/dracon-load-latest-database-action@v0
          with: 
            OUTPUT_DIR: ${{github.workspace}}/${{ env.DRACON_DIR}}/enricher-db/
        - name: run_enricher
          run: |
           sudo apt update && sudo apt install -y postgresql-client

           docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust --rm --network host postgres:13.6
           if [ -f $GITHUB_WORKSPACE/${{ env.DRACON_DIR}}/enricher-db/db.dump ]; then
              pg_restore -U postgres -h 127.0.0.1 -p 5432 --create -C --clean -d postgres < $GITHUB_WORKSPACE/${{ env.DRACON_DIR}}/enricher-db/db.dump
           fi

           export ENRICHER_READ_PATH=/code/${{ env.DRACON_DIR}}/producer-out/
           export ENRICHER_WRITE_PATH=/code/${{ env.DRACON_DIR}}/enricher-out/
           export ENRICHER_DB_CONNECTION='host=127.0.0.1 port=5432 user=postgres' 
           docker run -v $GITHUB_WORKSPACE:/code -e ENRICHER_READ_PATH -e ENRICHER_WRITE_PATH -e ENRICHER_DB_CONNECTION thoughtmachine/dracon-enricher:latest

           pg_dump -h 127.0.0.1 -p 5432 -d postgres -U postgres -w -Fp --clean --no-owner --no-privileges --no-acl --if-exists --inserts --no-comments > $GITHUB_WORKSPACE/${{ env.DRACON_DIR}}/enricher-db/db.dump
           ls -lah $GITHUB_WORKSPACE/${{ env.DRACON_DIR}}/enricher-db/db.dump
        - uses: actions/upload-artifact@v2
          with:
            name: dracon_enrichment_db
            path: $GITHUB_WORKSPACE/${{ env.DRACON_DIR}}/enricher-db/db.dump
            if-no-files-found: error
            retention-days: 90 # 3 months of backups should be enough
        - name: run_stdout_consumer
          run: echo ""
          ###
        - name: run_slack_consumer
          run: echo ""
          ###
