name: Run dracon
on:
  workflow_dispatch: # allow manual triggering
jobs:
    build:
      name: run-security-scans
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: run_gosec
          run: docker run -v $GITHUB_WORKSPACE:/code  securego/gosec -fmt json -r -no-fail -quiet -out /code/gosec_out.json /code/...
        - name: debug0
          run: ls -lah $GITHUB_WORKSPACE; cat $GITHUB_WORKSPACE/gosec_out.json
        - name:  parse_gosec
          run: docker run -v $GITHUB_WORKSPACE:/code  thoughtmachine/dracon-producer-gosec -in /code/gosec_out.json -out /code/gosec-producer-out
        - name: debug1
          run: ls -lah $GITHUB_WORKSPACE; cat $GITHUB_WORKSPACE/gosec-producer-out
        - name: fetch_db
          uses: northdpole/dracon-load-latest-database-action@v0
        - name: run_enricher
          run: echo "" # docker run -v $(GITHUB_WORKSPACE):/code 
          ###
        - name: save_enriched_db
          run: echo ""
          ###
        - name: run_stdout_consumer
          run: echo ""
          ###
        - name: run_slack_consumer
          run: echo ""
          ###
